services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: noteapp-frontend
    ports:
      - "5173:5173"
    networks:
      - noteapp-network

networks:
  noteapp-network:
    name: noteapp-network
    driver: bridge
