services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_HOST_PORT:-5173}:5173"
    networks:
      - noteapp-network

networks:
  noteapp-network:
    driver: bridge
