FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json .
RUN npm install --silent

COPY . .
RUN npm run build


FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

# Configuración para React Router (SPA — todas las rutas van al index.html)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 5173